version: "3.9"
services:
  dev:
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    environment:
      PORT: 3000
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules/
    ports:
      - "3000:3000"
