version: "3.9"
services:
  dev:
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules/
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
