---
apiVersion: v1
kind: Service
metadata:
  name: node-stress-service
spec:
  type: LoadBalancer 
  selector:
    app: node-stress
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-stress
  labels:
    app: node-stress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-stress
  template:
    metadata:
      labels:
        app: node-stress
    spec:
      containers:
      - name: node-stress
        image: licencjat:logger
        resources:
          limits:
            cpu: 500m
            memory: "128Mi"
          requests:
            cpu: 200m
            memory: "128Mi"
        ports:
        - containerPort: 3000
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: node-stress
spec:
  minReplicas: 2
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-stress
  metrics: 
  - type: Resource 
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource 
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---