apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-stress
  labels:
    app: node-stress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-stress
  template:
    metadata:
      labels:
        app: node-stress
    spec:
      containers:
      - name: node-stress
        image: maaasyn/licencjat:prod
        env:
          - name: PORT
            value: "3000"
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
          requests:
            cpu: "250m"
            memory: "96Mi"
        ports:
        - containerPort: 3000