apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-stress
  labels:
    app: node-stress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-stress
  template:
    metadata:
      labels:
        app: node-stress
    spec:
      containers:
      - name: node-stress
        image: licencjat:1.0.0
        resources:
          limits:
            cpu: 500m
            memory: "128Mi"
          requests:
            cpu: 200m
            memory: "128Mi"
        ports:
        - containerPort: 3000